### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by HrithikMittal** [pratikjaiswal15/loopbackauthrization#1]
After getting profile from here 
https://github.com/pratikjaiswal15/loopbackauthrization/blob/50c5cccb2920e6740b3e5778534ac7db72e364c3/src/services/custom-user.service.ts#L49

You will send it to create the token right?

**Comment by pratikjaiswal15** [comment]
Yes. See here
https://github.com/pratikjaiswal15/loopbackauthrization/blob/50c5cccb2920e6740b3e5778534ac7db72e364c3/src/controllers/user.controller.ts#L249
.

I got your point of adding role property in jwt service. And I have
actually added but still its not working.

**Comment by HrithikMittal** [comment]
Can you show me where you add it?

**Comment by pratikjaiswal15** [comment]
Here https://github.com/strongloop/loopback-next/blob/8c4100cc3911ef49d22c8f3f76dcf3bf997edc3b/extensions/authentication-jwt/src/services/jwt.service.ts#L63. 

I have added on my local laptop.

**Comment by pratikjaiswal15** [comment]
I have added it on my pc.
![IMG20200530000622](https://user-images.githubusercontent.com/31253688/83293647-9a93bc00-a209-11ea-913a-e404d3609f5a.jpg)

**Comment by pratikjaiswal15** [comment]
In my controller, I am using this token service https://github.com/strongloop/loopback-next/blob/8c4100cc3911ef49d22c8f3f76dcf3bf997edc3b/packages/authentication/src/services/token.service.ts#L28 

I also added roles property to userPRofile

**Comment by HrithikMittal** [comment]
Bro if you don't mind can we connect using team viewer?

**Comment by HrithikMittal** [comment]
Or If it possible can you create your project from start
and please use this repo it will help you 
https://github.com/HrithikMittal/loopback4-authorization
https://github.com/HrithikMittal/loopback4-auth

**Comment by pratikjaiswal15** [comment]
Okay, thank you for your help.
I think creating my own token service will solve this issue.

**Comment by HrithikMittal** [comment]
Ya, It will and Please also close the issue on loopback-next repo

**Comment by pratikjaiswal15** [comment]
yes.

**Comment by HrithikMittal** [comment]
Thank you and I also close this one.

**Comment by parul147** [comment]
pratikjaiswal15 can you please share your code of token service which helped you?
